apiVersion: v2
appVersion: 4.4.0 
description: |
  IBM Helm Chart to deploy MongoDB Enterprise on OpenShift Container
  Platform hosted on IBM Power systems.

  Documentation
  For additional details regarding install parameters see here
  https://docs.mongodb.com/manual/administration/install-enterprise/

  License
  By installing this product you accept the license terms.
  https://www.mongodb.com/community/licensing

keywords:
- IBM
- ppc64le
- Enterprise MongoDB
- RHOCP
- Database
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- name: IBM
name: ibm-mongodb-enterprise-helm 
version: 0.3.0
