apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
storageConfig:
  local:
    path: <path-to>/helm-mirroring/mirroring-tools-test/oc-mirror/mirror
mirror:
 helm:
  local:
    - name: test-mirror-helm
      path: <path-to>//helm-mirroring/charts/test-mirror-helm-0.3.0.tgz
