apiVersion: apps/v1
kind: Deployment
metadata:
    name: ibm-mongo-operands
spec:
    replicas: 1
    selector: 
        matchLabels: app: ibm-mongo-operands
    template:
        metadata:
            labels: app: ibm-mongo-operands
        spec:
            containers:
                - name: pause
                  image: k8s.gcr.io/pause:3.2
                - name: busybox
                  image: busybox:1.31.0
                  command: 
                    - sleep 
                    - "3600" 
