{{- if .Values.global.license }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.persistence.claims.name }}
  labels:
{{ include "ibm-mongodb-enterprise-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.global.persistence.claims.accessMode | quote }}
{{- if .Values.global.persistence.claims.storageClassName }}
  storageClassName: {{ .Values.global.persistence.claims.storageClassName | quote }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.global.persistence.claims.capacity }}{{ .Values.global.persistence.claims.capacityUnit }}"
{{- end }}
