kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4                                                      
storageConfig:                                                      
  registry:
    imageURL: example.com/mirror/oc-mirror-metadata                 
    skipTLS: false
mirror:
  additionalImages:
  - name: k8s.gcr.io/pause:3.2
  - name: quay.io/quay/busybox:latest
  - name: quay.io/nginx/nginx-ingress:latest
  